name: Win32-CI
on:
  push:
    branches: [master]
  pull_request:

env:
  KF5_VERSION: "5.98"
  KF5_FULLVER: "5.98.0"
  QT_VERSION: "5.15.2"
  CM_GENERATOR: "Visual Studio 16 2019"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          arch: win32_msvc2019
          version: ${{ env.QT_VERSION }}
      - name: Build Qt5 Libs
        run: |
          mkdir build_deps
          cd build_deps
          curl -LO https://download.kde.org/stable/frameworks/${Env:KF5_VERSION}/extra-cmake-modules-${Env:KF5_FULLVER}.zip
          curl -LO https://download.kde.org/stable/frameworks/${Env:KF5_VERSION}/syntax-highlighting-${Env:KF5_FULLVER}.zip
          cmake -E tar xf extra-cmake-modules-${Env:KF5_FULLVER}.zip
          cd extra-cmake-modules-${Env:KF5_FULLVER}
          mkdir build
          cd build
          cmake -G "${Env:CM_GENERATOR}" -A Win32 `
              "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${Env:QT_VERSION}/msvc2019" `
              "-DCMAKE_INSTALL_PREFIX=${Env:RUNNER_WORKSPACE}/Qt/${Env:QT_VERSION}/msvc2019" `
              -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release --target install
          cd ..\..
          cmake -E tar xf syntax-highlighting-${Env:KF5_FULLVER}.zip
          cd syntax-highlighting-${Env:KF5_FULLVER}
          mkdir build && cd build
          cmake -G "${Env:CM_GENERATOR}" -A Win32 `
              "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${Env:QT_VERSION}/msvc2019" `
              "-DCMAKE_INSTALL_PREFIX=${Env:RUNNER_WORKSPACE}/Qt/${Env:QT_VERSION}/msvc2019" `
              -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cmake --build . --config Release --target install
      - name: Build cctools
        run: |
          mkdir build
          cd build
          cmake -G "${Env:CM_GENERATOR}" -A Win32 `
            "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${Env:QT_VERSION}/msvc2019" `
            "-DCMAKE_INSTALL_PREFIX=${Env:GITHUB_WORKSPACE}/Dist" `
            -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cmake --build . --config Release --target install
      - name: Package cctools
        run: |
          $buildver = ((git describe --tags --dirty) | Out-String).Trim()
          $Env:VCINSTALLDIR = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC"
          cd "${Env:GITHUB_WORKSPACE}\Dist"
          cmake -E copy "${Env:GITHUB_WORKSPACE}\LICENSE" `
              "${Env:GITHUB_WORKSPACE}\LICENSE-oxygen-icon-theme" `
              "${Env:GITHUB_WORKSPACE}\changelog.txt" `
              "${Env:RUNNER_WORKSPACE}\Qt\${Env:QT_VERSION}\msvc2019\bin\KF5SyntaxHighlighting.dll" `
              .
          windeployqt CCEdit.exe CC2Edit.exe CCHack.exe CCPlay.exe KF5SyntaxHighlighting.dll `
              --release --no-angle --no-opengl-sw
          iscc setup.iss
          cmake -E rename CCTools.exe "..\CCTools-${buildver}.exe"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CCTools-win32
          path: CCTools-*.*
